# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20151018_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='short_name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
