# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.IntegerField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
