# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160111_1024'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('forum_id', 'user_id')]),
        ),
    ]
