# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160111_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
